name: universal_flutter_utils

description: "A powerful, all-in-one Flutter utilities and widgets package to speed up development and keep your code clean."
version: 0.0.6

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

homepage: https://github.com/dawasim/universal_flutter_utils/blob/main/README.md

license: MIT

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.17
  pinput: ^6.0.1
  fluttertoast: ^8.2.12

  shimmer_animation: ^2.2.2
  scroll_to_index: ^3.0.1

  intl: ^0.20.2
  get: ^4.7.3
  shared_preferences: ^2.5.2

  path_provider: ^2.1.5
  file_picker: ^10.3.3
  permission_handler: ^11.4.0
  image_picker: ^1.1.2
  image: ^4.5.3
  custom_image_crop: ^0.1.1
  audio_waveforms: ^1.2.0
  flutter_native_contact_picker: ^0.0.10
  open_filex: ^4.6.0

  # Location
  map_location_picker: ^1.3.3
  location: ^8.0.1
  form_builder_extra_fields: ^12.0.0

  # Display share prompt
  share_plus: ^12.0.1

  ## Server communication
  http: ^1.5.0
  dio: ^5.7.0
  socket_io_client: ^3.1.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  flutter_widget_from_html_core: ^0.16.1
  geolocator: ^13.0.2
  flutter_typeahead: ^5.2.0

  # Video Player
  chewie: ^1.10.0
  video_player: ^2.9.3

  encrypt: ^5.0.3
  convert: ^3.1.2
  crypto: ^3.0.6
  path: ^1.9.1
  html: ^0.15.6
  flutter_html: ^3.0.0-beta.2 # The 3.0.0 series is still largely in beta/RC for this package

  # Biometric Recognition
  local_auth: ^3.0.0

  # Firebase
  firebase_core: ^4.3.1
  firebase_auth: ^6.1.4
  firebase_crashlytics: ^5.0.7

  # Push Notifications
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.0.0
  flutter_app_badge_control: ^0.0.2

  # Social login
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^7.0.1
  flutter_login_facebook: ^2.0.1

  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  assets:
    - assets/folder.svg
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
